# .gitpod.yml
tasks:
  - init: |
      docker-compose up -d mysql redis
      docker-compose up init
    command: docker-compose up app

ports:
  - port: 3000
    onOpen: open-browser
  - port: 8080
    onOpen: ignore

github:
  prebuilds:
    # Enable for the main branch
    branches: true
    # Enable for pull requests
    pullRequests: true

vscode:
  extensions:
    - ms-azuretools.vscode-docker

docker:
  image: gitpod/workspace-full
  composefile: ./docker-compose.yml
