tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up

ports:
  - port: 3000
    onOpen: open-browser
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker

docker:
  image: gitpod/workspace-full
  composefile: ./docker-compose.yml
